### ISSUE TITLE
What is the best online Apparel design tool and webshop?

### ISSUE THREAD

**Issue by aschrijver** [engagingspaces/humane-tech-artwork#1]
There are many great companies that print T-shirts and the like at low-cost and have great online tools as well as webshops to make this really easy. Your help is needed to select the best one! Let's try to find the one that complies best to Humane Tech principles and reward them with our patronage.

The requirements are:

- **Low-cost**  - in production as well as sales prices (but humanely produced)

- **World-wide delivery** - our (current and future) members are _everywhere_!

- **Easy-to-use** - preferably a DIY web app where you can bring all things together easily

> Note: Do **not** just advertise arbitrary products and services here. Only suggest serious contenders!

**Comment by om-design** [comment]
Spreadsheet is pretty equitable and has global reach.

**Comment by aschrijver** [comment]
The design contest is over. The repository is repurposed as a community artwork project. Closing issue.
