### ISSUE TITLE
Should I add the CHT URL to my submission The Rise of Yang?

### ISSUE THREAD

**Issue by aschrijver** [engagingspaces/humane-tech-artwork#3]
Hi!

This is my current submission:

![The Rise of Yang](https://github.com/engagingspaces/humane-tech-artwork/raw/master/submissions/the-rise-of-yang/humane-tech_the-rise-of-yang_white.png)

However it does not contain a link to the humanetech.com website, which is a pity. I am wondering if I should add. I have tried to include the text `humanetech.com` (lowercase) on top of the Yin-Yang symbol more or less the same width as the CHT title below, but it does not look all that appealing. I used a very thin font, and Lato Hairline-thin, or Lato Ultra-light looked best.
On the other hand, I like the simplicity of current design, and with more text (header or additional tagline) it looks more crowded.

What is your opinion on this?

PS I didn't save this change, but if you need to see this visually I can recreate it..

**Comment by micheleminno** [comment]
Yes, you should add it in my opinion.

**Comment by aschrijver** [comment]
Thanks, I will recreate it and have both versions available :)

I was also thinking that for a T-shirt the URL could be on the front instead, maybe in a small square patch near the heart (and use e.g. the heart symbol from **Gears of the Heart** with it).

**Comment by aschrijver** [comment]
On 2nd thought: I will try a more 'traditional' layout with title + tagline on top, the url at the bottom, and the symbol slightly enlarged for visual appeal.

Probably better UX practices that way :)

**Comment by micheleminno** [comment]
I was wondering if you really need: 

`[Center for Humane Technology]`

if you show the url.

**Comment by aschrijver** [comment]
I think that is needed, otherwise it is unclear in meaning, looking like just some DotCom site. Plus I find it visually appealing with those brackets surrounding it :)

**Comment by aschrijver** [comment]
The design contest is over. The repository is repurposed as a community artwork project. Closing issue.
